import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "@/app/_components/layout/Header";

import "./globals.css";
import Script from "next/script";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script
          id="theme-initialization"
          src="/init-theme.js"
          strategy="beforeInteractive"
        />
      </head>
      <body
        className="bg-foreground text-background dark:bg-background dark:text-foreground px-14"
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />

        {children}
      </body>
    </html>
  );
}
