import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="px-14 pt-12 flex flex-row justify-between">
          <Link href="/" aria-label="return to home page">
            <Image
              className="dark:invert"
              src="/fonts-ninja.svg"
              alt="fonts ninja logo"
              width={24}
              height={26}
              priority
            />
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
